apiVersion: v1
kind: Service
metadata:
    name: my-quarkus
    annotations:
        dev.okteto.com/auto-ingress: "true"    
spec:
    selector:
        app: my-quarkus
    ports:
    - port: 8080
      targetPort: 8080